Allow unguided assembly
biowdl/expression-quantification pull request #10
Opened 2018-11-15 16:26 UTC by rhpvorderman

2018-11-15 16:27 UTC, rhpvorderman commented
Other solutions are possible here. Making the reference gtf completely optional and disabling the counting.

2018-11-16 08:08 UTC, DavyCats submitted a review, later dismissed

2018-11-19 15:28 UTC, DavyCats requested changes

2018-11-19 15:28 UTC, DavyCats commented on multi-bam-quantify.wdl
> +        File? referenceGtfFile # Not providing the reference gtf will have stringtie do an unguided assembly"
Why is there a `"` at the end of this comment?

2018-11-19 15:28 UTC, DavyCats commented on multi-bam-quantify.wdl
> +        Array[File] gffFiles = stringtie.assembledTranscripts
I'm wondering if it would be a good idea to make this a `Pair[String, File]` (sample ID, GTF file)?

Also the Stringtie manual states it outputs a GTF file, not GFF, might be good to be consistent in this.

2018-11-20 08:02 UTC, rhpvorderman commented on multi-bam-quantify.wdl
> +        Array[File] gffFiles = stringtie.assembledTranscripts
:+1:

2018-11-20 08:57 UTC, DavyCats requested changes

2018-11-20 08:57 UTC, DavyCats commented on multi-bam-quantify.wdl
> +                assembledTranscriptsFile = strintieDir + sampleId + ".gff",
Could you change this to `.gtf` as well?

2018-11-20 09:08 UTC, DavyCats approved these changes

2018-11-20 09:52 UTC, merged